In [2]:
import numpy as np

In [3]:
ml = [1, 2, 3, 4, 6]
ma = np.array(ml)

In [4]:
print(ma)

[1 2 3 4 6]


In [5]:
type(ma)

numpy.ndarray

In [6]:
pmat = [ [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
nmat = np.array(pmat)

In [8]:
nmat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
type(nmat)

numpy.ndarray

In [10]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
x = np.linspace(0, 5, 40)

In [14]:
x

array([0.        , 0.12820513, 0.25641026, 0.38461538, 0.51282051,
       0.64102564, 0.76923077, 0.8974359 , 1.02564103, 1.15384615,
       1.28205128, 1.41025641, 1.53846154, 1.66666667, 1.79487179,
       1.92307692, 2.05128205, 2.17948718, 2.30769231, 2.43589744,
       2.56410256, 2.69230769, 2.82051282, 2.94871795, 3.07692308,
       3.20512821, 3.33333333, 3.46153846, 3.58974359, 3.71794872,
       3.84615385, 3.97435897, 4.1025641 , 4.23076923, 4.35897436,
       4.48717949, 4.61538462, 4.74358974, 4.87179487, 5.        ])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
arr = np.arange(25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
r = np.random.randint(0, 50, 10)

In [24]:
print(r)

[ 5 30  5 33 16 10 11 20 44 43]


In [25]:
print(r)

[ 5 30  5 33 16 10 11 20 44 43]


In [26]:
ranarr = np.random.randint(0, 50, 10)

In [27]:
ranarr.max()

44

In [28]:
print(ranarr)

[44 18 13 33 23 36 44 28 30 10]


In [29]:
ranarr.argmax()

0