In [ ]:
# numpy arrays
    1. 1-d and 2-d
    2. create from python list
# create arrays
    np.arange(0, 11, 2)
    np.zeros((2, 5))
    np.ones((2, 5))
    np.linspace(0, 5, 11)
    np.eye(5)
# random numbers
    np.random.rand()
    np.random.randn()
    np.random.randint()
# reshape
    my_array.reshape(5, 5)
# max and min
    my_array.max(), my_array.min()
    my_array.argmax(), my_array.argmin()
# some properties
    my_array.shape
    my_array.dtype

# copy vs view; broadcast
# default to view to avoid memory issue
    arr_view = my_array[2:10]
    arr_copy = my_array.copy()

# indexing and selections
# prefer single bracket indexing over double brackets indexing
    my_2darray[:2, 1:]
# conditional selection
    bool_array = my_array > 5
    my_array[bool_array]

# numpy operations: array with array; array with scalars by broadcasting; universal array functions

In [ ]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [5]:
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(10)  # uniformly distributed

array([0.95951885, 0.6069962 , 0.83694451, 0.21376561, 0.28320678,
       0.91515948, 0.48557654, 0.76547002, 0.76152137, 0.49706999])

In [14]:
np.random.randn(10)  # Gaussian/Normal distribution

array([-0.50520104, -0.3134174 ,  1.50477853, -0.51066162,  0.92383841,
       -0.16124375,  0.12279709,  0.45584359,  1.1790491 , -0.44208264])

In [15]:
np.random.randn(5, 5,)

array([[ 0.52684827,  0.43588337,  0.5991914 , -0.85701895, -1.06694629],
       [-0.06121626,  0.27401157, -0.43767164, -1.52334472,  0.16042777],
       [ 0.51469723,  0.83525409,  0.25627714, -0.8441833 ,  0.3068599 ],
       [-0.56306335,  1.16968483,  1.41816312,  0.95173287, -1.5681655 ],
       [ 0.40143374,  0.39444991,  0.51182475, -0.25515116, -1.27417369]])

In [16]:
np.random.randint(0, 100, 10)  # "discrete uniform” distribution

array([69, 47, 48, 97, 88, 65, 16, 50, 16, 11])

In [18]:
np.arange(25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
randarr = np.random.randint(0, 100, 25)

In [23]:
randarr, randarr.max(), randarr.min(), randarr.argmax(), randarr.argmin()

(array([91, 91, 47, 53, 94, 53, 64, 46,  3, 56, 47,  5, 52, 85, 79, 73, 61,
        60, 76, 58, 80, 13, 21, 38, 85]), 94, 3, 4, 8)

In [26]:
randarr.shape, randarr.dtype

((25,), dtype('int64'))

In [27]:
# indexing and selections

In [29]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
a1 = arr[1:8]
a1

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
a1[0] = 5
a1

array([5, 2, 3, 4, 5, 6, 7])

In [32]:
arr

array([ 0,  5,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[:5], arr[5:]

(array([0, 5, 2, 3, 4]), array([ 5,  6,  7,  8,  9, 10]))

In [34]:
# broadcast
arr[2:5] = 100
arr

array([  0,   5, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [35]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr2d = np.arange(5, 46, 5).reshape(3, 3)
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [44]:
arr2d[1][2], arr2d[1, 2]  # double brackets vs single bracket: the later is prefered

(30, 30)

In [47]:
arr2d[:2, 1:]  # you cannot use double brackets to do this

array([[10, 15],
       [25, 30]])

In [48]:
arr2d[:2][1:]

array([[20, 25, 30]])

In [50]:
# conditional selection
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
bool_array = arr > 5
bool_array

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [54]:
arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [55]:
a2d = np.arange(50).reshape(5, 10)
a2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [56]:
a2d[1:3, :5]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [57]:
# operations
arr = np.arange(0, 11)
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [58]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
arr / arr

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [60]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [61]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])